# Generated by Django 4.1.2 on 2022-10-14 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_member_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='password',
            field=models.CharField(default='123456', max_length=200),
        ),
    ]
