# Generated by Django 4.0.5 on 2022-10-17 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writings', '0005_alter_writingspost_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writingspost',
            name='title',
            field=models.CharField(max_length=300),
        ),
    ]
