# Generated by Django 4.0.5 on 2022-10-25 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writings', '0008_alter_writingspost_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writingspost',
            name='category',
            field=models.CharField(choices=[('Nutrition', 'Nutrition'), ('Diseases', 'Disease'), ('Beauty', 'Beauty')], max_length=50),
        ),
    ]
