# Generated by Django 4.0.5 on 2022-10-16 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('writings', '0003_remove_writingspost_image_cover'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='writingspost',
            name='day',
        ),
        migrations.RemoveField(
            model_name='writingspost',
            name='excerpt',
        ),
        migrations.RemoveField(
            model_name='writingspost',
            name='featured',
        ),
        migrations.RemoveField(
            model_name='writingspost',
            name='month',
        ),
    ]
