# Generated by Django 4.0.5 on 2022-10-16 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('writings', '0002_rename_blogpost_writingspost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='writingspost',
            name='image_cover',
        ),
    ]
