# Generated by Django 4.0.5 on 2022-10-16 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writings', '0004_remove_writingspost_day_remove_writingspost_excerpt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writingspost',
            name='category',
            field=models.CharField(choices=[('nutrition', 'Nutrition'), ('disease', 'Disease'), ('beauty', 'Beauty')], default='nutrition', max_length=50),
        ),
    ]
