# Generated by Django 4.1.1 on 2022-10-03 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_member_gender_member_username_alter_member_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='createDatetime',
            field=models.DateTimeField(null=True),
        ),
    ]
