# Generated by Django 4.1.1 on 2022-10-03 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_react_remove_member_age_remove_member_first_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='React',
        ),
        migrations.RemoveField(
            model_name='member',
            name='createDatetime',
        ),
        migrations.AddField(
            model_name='member',
            name='identity',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Normal'), (1, 'Professional')], default=0),
        ),
    ]
