# Generated by Django 4.1.1 on 2022-10-04 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_delete_react_remove_member_createdatetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='identity',
            field=models.BooleanField(choices=[(0, 'Normal'), (1, 'Professional')], default=0, null=True),
        ),
    ]
