# Generated by Django 4.1.1 on 2022-10-04 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_member_identity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='identity',
            field=models.CharField(default='Normal', max_length=16),
        ),
    ]
